language: node_js
node_js:
  - "8"
cache:
  directories:
    - "node_modules"
    - "server/node_modules"
    - "client/node_modules"
install:
    - npm install
    - npm install --prefix client
    - npm install --prefix server
script:
  - npm run test
  - npm run build